# Generated by Django 4.2 on 2023-09-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Friend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_name", models.CharField(max_length=100)),
                ("age", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=100)),
                ("likes", models.CharField(max_length=100)),
                ("dislikes", models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.CharField(max_length=100)),
                ("user_age", models.CharField(max_length=100)),
                ("user_gender", models.CharField(max_length=100)),
            ],
        ),
    ]
